/* The following code was generated by JFlex 1.4.3 on 8/11/15 8:48 AM */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/11/15 8:48 AM from the specification file
 * <tt>PLXC.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\50\2\0\1\51\23\0\1\47\1\17\2\0\1\46\1\5"+
    "\1\22\1\0\1\6\1\7\1\3\1\1\1\15\1\2\1\44\1\4"+
    "\1\42\11\43\1\0\1\14\1\20\1\16\1\21\2\0\4\46\1\45"+
    "\25\46\1\12\1\0\1\13\1\0\1\46\1\0\1\41\2\46\1\33"+
    "\1\26\1\25\1\46\1\32\1\24\2\46\1\27\1\46\1\37\1\34"+
    "\1\36\1\46\1\35\1\30\1\40\2\46\1\31\3\46\1\10\1\23"+
    "\1\11\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\1\11\23\2\24\1\1\1\25"+
    "\1\1\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\6\23\1\37\1\23\1\40\1\0\1\41"+
    "\1\0\1\41\1\42\1\23\1\43\5\23\1\0\1\41"+
    "\1\23\1\44\1\45\3\23\1\46\1\47\1\23\1\50"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\52\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\52\0\52\0\52\0\52\0\250"+
    "\0\322\0\374\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8"+
    "\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348"+
    "\0\u0372\0\52\0\u039c\0\52\0\52\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\u0222\0\u03c6\0\u03f0\0\u041a\0\u0444"+
    "\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0222\0\u0516\0\u031e\0\u0372"+
    "\0\u0540\0\u0222\0\u056a\0\u0222\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\u0666\0\u0666\0\u0690\0\u0222\0\u0222\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0222\0\u0222\0\u0738\0\u0222\0\u0222";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\31\1\34\2\31\1\35\1\31\1\36"+
    "\1\31\1\37\1\40\1\41\2\31\1\42\1\43\1\2"+
    "\53\0\1\44\52\0\1\45\65\0\1\46\51\0\1\47"+
    "\51\0\1\50\51\0\1\51\55\0\1\52\52\0\1\53"+
    "\52\0\1\31\1\54\11\31\1\55\4\31\1\0\2\31"+
    "\27\0\3\31\1\56\4\31\1\57\7\31\1\0\2\31"+
    "\27\0\3\31\1\60\14\31\1\0\2\31\27\0\20\31"+
    "\1\0\2\31\27\0\14\31\1\61\3\31\1\0\2\31"+
    "\27\0\6\31\1\62\11\31\1\0\2\31\27\0\10\31"+
    "\1\63\7\31\1\0\2\31\27\0\11\31\1\64\6\31"+
    "\1\0\2\31\27\0\10\31\1\65\7\31\1\0\2\31"+
    "\31\0\1\66\13\0\2\67\1\70\1\66\32\0\1\66"+
    "\13\0\2\40\1\70\1\66\46\0\2\71\57\0\1\42"+
    "\24\0\14\31\1\72\3\31\1\0\2\31\27\0\10\31"+
    "\1\73\7\31\1\0\2\31\27\0\11\31\1\74\6\31"+
    "\1\0\2\31\27\0\4\31\1\75\13\31\1\0\2\31"+
    "\27\0\2\31\1\76\15\31\1\0\2\31\27\0\1\77"+
    "\17\31\1\0\2\31\27\0\5\31\1\100\12\31\1\0"+
    "\2\31\27\0\1\101\17\31\1\0\2\31\4\0\2\102"+
    "\37\0\2\103\34\0\1\66\13\0\2\71\1\0\1\66"+
    "\30\0\15\31\1\104\2\31\1\0\2\31\27\0\2\31"+
    "\1\105\15\31\1\0\2\31\27\0\12\31\1\106\5\31"+
    "\1\0\2\31\27\0\3\31\1\107\14\31\1\0\2\31"+
    "\27\0\13\31\1\110\4\31\1\0\2\31\27\0\13\31"+
    "\1\111\4\31\1\0\2\31\45\0\2\103\32\0\14\31"+
    "\1\112\3\31\1\0\2\31\27\0\2\31\1\113\15\31"+
    "\1\0\2\31\27\0\14\31\1\114\3\31\1\0\2\31"+
    "\27\0\14\31\1\115\3\31\1\0\2\31\27\0\10\31"+
    "\1\116\7\31\1\0\2\31\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1890];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\13\11\22\1\1\11\1\1\10\11"+
    "\12\1\1\0\1\1\1\0\11\1\1\0\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public static int actualTag = 0;

	public static String newTag(){
		return "L"+(actualTag++);	
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { return new Symbol(sym.CC);
          }
        case 42: break;
        case 33: 
          { return new Symbol(sym.FLOATN, yytext());
          }
        case 43: break;
        case 6: 
          { return new Symbol(sym.MOD);
          }
        case 44: break;
        case 17: 
          { return new Symbol(sym.LOW);
          }
        case 45: break;
        case 15: 
          { return new Symbol(sym.ASIG);
          }
        case 46: break;
        case 25: 
          { return new Symbol(sym.NEQ);
          }
        case 47: break;
        case 9: 
          { return new Symbol(sym.ALL);
          }
        case 48: break;
        case 26: 
          { return new Symbol(sym.LOE);
          }
        case 49: break;
        case 11: 
          { return new Symbol(sym.AC);
          }
        case 50: break;
        case 29: 
          { return new Symbol(sym.OR);
          }
        case 51: break;
        case 20: 
          { return new Symbol(sym.INTEGER, yytext());
          }
        case 52: break;
        case 24: 
          { return new Symbol(sym.EQ);
          }
        case 53: break;
        case 32: 
          { return new Symbol(sym.TO, newTag());
          }
        case 54: break;
        case 38: 
          { return new Symbol(sym.FLOAT);
          }
        case 55: break;
        case 35: 
          { return new Symbol(sym.FOR, newTag());
          }
        case 56: break;
        case 40: 
          { return new Symbol(sym.PRINT);
          }
        case 57: break;
        case 39: 
          { return new Symbol(sym.WHILE, newTag());
          }
        case 58: break;
        case 13: 
          { return new Symbol(sym.PYC);
          }
        case 59: break;
        case 36: 
          { return new Symbol(sym.ELSE);
          }
        case 60: break;
        case 37: 
          { return new Symbol(sym.STEP);
          }
        case 61: break;
        case 14: 
          { return new Symbol(sym.COMMA);
          }
        case 62: break;
        case 8: 
          { return new Symbol(sym.CP);
          }
        case 63: break;
        case 2: 
          { return new Symbol(sym.MAS);
          }
        case 64: break;
        case 27: 
          { return new Symbol(sym.GOE);
          }
        case 65: break;
        case 31: 
          { return new Symbol(sym.DO, newTag());
          }
        case 66: break;
        case 4: 
          { return new Symbol(sym.POR);
          }
        case 67: break;
        case 10: 
          { return new Symbol(sym.CLL);
          }
        case 68: break;
        case 7: 
          { return new Symbol(sym.AP);
          }
        case 69: break;
        case 23: 
          { return new Symbol(sym.DECR);
          }
        case 70: break;
        case 18: 
          { return new Symbol(sym.GRE);
          }
        case 71: break;
        case 3: 
          { return new Symbol(sym.MENOS);
          }
        case 72: break;
        case 1: 
          { /*throw new Error("Illegal character <"+yytext()+">");*/
          }
        case 73: break;
        case 34: 
          { return new Symbol(sym.INT);
          }
        case 74: break;
        case 22: 
          { return new Symbol(sym.INCR);
          }
        case 75: break;
        case 41: 
          { return new Symbol(sym.DOWNTO, newTag());
          }
        case 76: break;
        case 16: 
          { return new Symbol(sym.NOT);
          }
        case 77: break;
        case 28: 
          { return new Symbol(sym.AND);
          }
        case 78: break;
        case 30: 
          { return new Symbol(sym.IF, newTag());
          }
        case 79: break;
        case 5: 
          { return new Symbol(sym.DIV);
          }
        case 80: break;
        case 19: 
          { return new Symbol(sym.IDENT, yytext());
          }
        case 81: break;
        case 21: 
          { 
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
